/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Swing;

/**
 *
 * @author java
 */
public class getor extends javax.swing.JFrame {

    /**
     * Creates new form getor
     */
    public getor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTotalactivosinmobiliarios = new javax.swing.JLabel();
        lblTotalactivosfinacieros = new javax.swing.JLabel();
        intTotalclientesgestores = new javax.swing.JTextField();
        intTotalactiivosinmobiliarios = new javax.swing.JTextField();
        intTotalactivosfinancieros = new javax.swing.JTextField();
        lblPreguntagestores = new javax.swing.JLabel();
        lblGestores = new javax.swing.JLabel();
        btnInmobiliariosgestores = new javax.swing.JButton();
        btnFinancierosgestores = new javax.swing.JButton();
        lblResumen = new javax.swing.JLabel();
        lblTotalclientesgestores = new javax.swing.JLabel();
        jTextNombregestor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTotalactivosinmobiliarios.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTotalactivosinmobiliarios.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotalactivosinmobiliarios.setText("Total Activos Inmobiliarios");

        lblTotalactivosfinacieros.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTotalactivosfinacieros.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotalactivosfinacieros.setText("Total Activos Financieros");

        intTotalclientesgestores.setEditable(false);
        intTotalclientesgestores.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        intTotalclientesgestores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intTotalclientesgestoresActionPerformed(evt);
            }
        });

        intTotalactiivosinmobiliarios.setEditable(false);
        intTotalactiivosinmobiliarios.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        intTotalactivosfinancieros.setEditable(false);
        intTotalactivosfinancieros.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblPreguntagestores.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblPreguntagestores.setText("¿Qué tipo de activo quieres consultar?");

        lblGestores.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblGestores.setText("Bienvenido");

        btnInmobiliariosgestores.setText("Activos Inmobiliarios");
        btnInmobiliariosgestores.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnFinancierosgestores.setText("Activos Financieros");
        btnFinancierosgestores.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblResumen.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblResumen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResumen.setText("RESUMEN ");

        lblTotalclientesgestores.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTotalclientesgestores.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotalclientesgestores.setText("Total Clientes");

        jTextNombregestor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextNombregestor.setText("NOMBRE DE GESTOR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblTotalactivosinmobiliarios)
                                        .addGap(63, 63, 63))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblTotalactivosfinacieros)
                                            .addComponent(lblTotalclientesgestores, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(btnInmobiliariosgestores, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnFinancierosgestores)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(intTotalactivosfinancieros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(intTotalactiivosinmobiliarios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(intTotalclientesgestores, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(lblPreguntagestores, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jTextNombregestor, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(lblResumen, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(77, 77, 77)
                    .addComponent(lblGestores, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(268, Short.MAX_VALUE)))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblTotalactivosfinacieros, lblTotalactivosinmobiliarios, lblTotalclientesgestores});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnFinancierosgestores, btnInmobiliariosgestores});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jTextNombregestor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblResumen)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(intTotalclientesgestores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(intTotalactiivosinmobiliarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(intTotalactivosfinancieros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTotalclientesgestores)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTotalactivosinmobiliarios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTotalactivosfinacieros)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(lblPreguntagestores, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInmobiliariosgestores)
                    .addComponent(btnFinancierosgestores))
                .addGap(36, 36, 36))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addComponent(lblGestores)
                    .addContainerGap(255, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void intTotalclientesgestoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intTotalclientesgestoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_intTotalclientesgestoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(getor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(getor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(getor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(getor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new getor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnFinancierosgestores;
    public javax.swing.JButton btnInmobiliariosgestores;
    public javax.swing.JTextField intTotalactiivosinmobiliarios;
    public javax.swing.JTextField intTotalactivosfinancieros;
    public javax.swing.JTextField intTotalclientesgestores;
    public javax.swing.JTextField jTextNombregestor;
    private javax.swing.JLabel lblGestores;
    private javax.swing.JLabel lblPreguntagestores;
    private javax.swing.JLabel lblResumen;
    private javax.swing.JLabel lblTotalactivosfinacieros;
    private javax.swing.JLabel lblTotalactivosinmobiliarios;
    private javax.swing.JLabel lblTotalclientesgestores;
    // End of variables declaration//GEN-END:variables
}
