/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.ctrlVistaClientes;
import Modelo.clientes;
import Modelo.conexion;
import javax.swing.table.*;

/**
 *
 * @author java
 */
public class vistaActivosCliente extends javax.swing.JFrame {

    DefaultTableModel modelotabla;

    /**
     * Creates new form CRUD
     */
    public vistaActivosCliente() {
        initComponents();
        this.modelotabla = (DefaultTableModel) tablaActivosInmobiliariosCliente.getModel();
        //listar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnFinanzas = new javax.swing.JButton();
        btnInmuebles = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        panelInmobiliarios = new javax.swing.JScrollPane();
        tablaActivosInmobiliariosCliente = new javax.swing.JTable();
        panelFinancieros = new javax.swing.JScrollPane();
        tablaActivosFinancierosCliente = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CRUD MySQL");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(733, 480));
        getContentPane().setLayout(null);

        jLabel1.setText("¿Qué quieres ver?");
        Menu.add(jLabel1);

        btnFinanzas.setText("Finanzas");
        btnFinanzas.setMaximumSize(new java.awt.Dimension(83, 22));
        btnFinanzas.setMinimumSize(new java.awt.Dimension(83, 22));
        btnFinanzas.setPreferredSize(new java.awt.Dimension(83, 22));
        Menu.add(btnFinanzas);

        btnInmuebles.setText("Inmuebles");
        btnInmuebles.setMaximumSize(new java.awt.Dimension(83, 22));
        btnInmuebles.setMinimumSize(new java.awt.Dimension(83, 22));
        btnInmuebles.setPreferredSize(new java.awt.Dimension(83, 22));
        Menu.add(btnInmuebles);

        btnVolver.setText("Volver");
        btnVolver.setMaximumSize(new java.awt.Dimension(83, 22));
        btnVolver.setMinimumSize(new java.awt.Dimension(83, 22));
        btnVolver.setPreferredSize(new java.awt.Dimension(83, 22));
        Menu.add(btnVolver);

        getContentPane().add(Menu);
        Menu.setBounds(6, 6, 110, 120);

        tablaActivosInmobiliariosCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tipo", "Ingreso Anual", "Coste Mantenimiento", "Coste Impuestos", "Valor", "Balance"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaActivosInmobiliariosCliente.setPreferredSize(new java.awt.Dimension(450, 300));
        panelInmobiliarios.setViewportView(tablaActivosInmobiliariosCliente);
        if (tablaActivosInmobiliariosCliente.getColumnModel().getColumnCount() > 0) {
            tablaActivosInmobiliariosCliente.getColumnModel().getColumn(0).setPreferredWidth(100);
            tablaActivosInmobiliariosCliente.getColumnModel().getColumn(1).setPreferredWidth(100);
            tablaActivosInmobiliariosCliente.getColumnModel().getColumn(2).setPreferredWidth(100);
            tablaActivosInmobiliariosCliente.getColumnModel().getColumn(3).setPreferredWidth(100);
        }

        jLayeredPane1.add(panelInmobiliarios);
        panelInmobiliarios.setBounds(10, 10, 510, 400);

        tablaActivosFinancierosCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Tipo", "Valor", "Ingresos Alquiler", "Costes Comunidad", "Costes Impuestos", "Costes Servicios", "Balance"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaActivosFinancierosCliente.setPreferredSize(new java.awt.Dimension(450, 300));
        panelFinancieros.setViewportView(tablaActivosFinancierosCliente);
        if (tablaActivosFinancierosCliente.getColumnModel().getColumnCount() > 0) {
            tablaActivosFinancierosCliente.getColumnModel().getColumn(0).setPreferredWidth(100);
            tablaActivosFinancierosCliente.getColumnModel().getColumn(1).setPreferredWidth(100);
            tablaActivosFinancierosCliente.getColumnModel().getColumn(2).setPreferredWidth(100);
            tablaActivosFinancierosCliente.getColumnModel().getColumn(3).setPreferredWidth(100);
        }

        jLayeredPane1.add(panelFinancieros);
        panelFinancieros.setBounds(10, 10, 510, 400);

        getContentPane().add(jLayeredPane1);
        jLayeredPane1.setBounds(124, 6, 580, 410);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaActivosCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaActivosCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaActivosCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaActivosCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaClientes().setVisible(true);
            }

        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaClientes().setVisible(true);
            }

        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaClientes().setVisible(true);
            }

        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaClientes().setVisible(true);
            }

        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaClientes().setVisible(true);
            }

        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaClientes().setVisible(true);
            }

        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaClientes().setVisible(true);
            }

        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaClientes().setVisible(true);
            }

        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaClientes().setVisible(true);
            }

        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaClientes().setVisible(true);
            }

        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaClientes().setVisible(true);
            }

        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaClientes().setVisible(true);
            }

        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaClientes().setVisible(true);
            }

        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaClientes().setVisible(true);
            }

        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaClientes().setVisible(true);
            }

        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaClientes().setVisible(true);
            }

        });*/
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Menu;
    public javax.swing.JButton btnFinanzas;
    public javax.swing.JButton btnInmuebles;
    public javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    public javax.swing.JScrollPane panelFinancieros;
    public javax.swing.JScrollPane panelInmobiliarios;
    public javax.swing.JTable tablaActivosFinancierosCliente;
    public javax.swing.JTable tablaActivosInmobiliariosCliente;
    // End of variables declaration//GEN-END:variables
}
