/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.ctrlVistaClientes;
import Modelo.clientes;
import Modelo.conexion;
import javax.swing.table.*;

/**
 *
 * @author java
 */
public class vistaActivosClienteFinanza extends javax.swing.JFrame {

    DefaultTableModel modelotabla;

    /**
     * Creates new form CRUD
     */
    public vistaActivosClienteFinanza() {
        initComponents();
        this.modelotabla = (DefaultTableModel) tablaActivosInmobiliariosCliente.getModel();
        //listar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaActivosInmobiliariosCliente = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CRUD MySQL");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(733, 480));
        getContentPane().setLayout(null);

        jLabel1.setText("¿Qué quieres hacer?");
        Menu.add(jLabel1);

        btnVolver.setText("Volver");
        btnVolver.setMaximumSize(new java.awt.Dimension(83, 22));
        btnVolver.setMinimumSize(new java.awt.Dimension(83, 22));
        btnVolver.setPreferredSize(new java.awt.Dimension(83, 22));
        Menu.add(btnVolver);

        getContentPane().add(Menu);
        Menu.setBounds(6, 6, 110, 120);

        tablaActivosInmobiliariosCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Tipo", "Ingreso Anual", "Coste Mantenimiento", "Coste Impuestos", "Valor", "Balance"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaActivosInmobiliariosCliente.setPreferredSize(new java.awt.Dimension(450, 300));
        jScrollPane1.setViewportView(tablaActivosInmobiliariosCliente);
        if (tablaActivosInmobiliariosCliente.getColumnModel().getColumnCount() > 0) {
            tablaActivosInmobiliariosCliente.getColumnModel().getColumn(0).setPreferredWidth(100);
            tablaActivosInmobiliariosCliente.getColumnModel().getColumn(1).setPreferredWidth(100);
            tablaActivosInmobiliariosCliente.getColumnModel().getColumn(2).setPreferredWidth(100);
            tablaActivosInmobiliariosCliente.getColumnModel().getColumn(3).setPreferredWidth(100);
        }

        jLayeredPane1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 320, 400);

        getContentPane().add(jLayeredPane1);
        jLayeredPane1.setBounds(124, 6, 340, 410);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaActivosClienteFinanza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaActivosClienteFinanza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaActivosClienteFinanza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaActivosClienteFinanza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaClientes().setVisible(true);
            }

        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaClientes().setVisible(true);
            }

        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaClientes().setVisible(true);
            }

        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaClientes().setVisible(true);
            }

        });*/
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Menu;
    public javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tablaActivosInmobiliariosCliente;
    // End of variables declaration//GEN-END:variables
}
